services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    hostname: selenium
    privileged: true
  usar-mailer:
    build: .
    image: sujaldev/usar-mailer:latest
    depends_on:
      - selenium
    volumes:
      - ./data:/app/data/
    environment:
      - PASSWORD=${PASSWORD}
      - SENDGRID_KEY=${SENDGRID_KEY}
      - INTERVAL=${INTERVAL}